# fly.toml app configuration file for magnum-consortium
app = "magnum-consortium"
primary_region = "yul"

# Build section to use the Dockerfile in your project
[build]
  dockerfile = "Dockerfile"

# HTTP service configuration
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
