# fly.toml app configuration file generated for magnum-consortium on 2024-11-23T17:36:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "magnum-consortium"
primary_region = "yul"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
