# Schema for the views plugins of the Views TimelineJS module.

views.style.timelinejs:
  type: views_style
  label: TimelineJS
  mapping:
    timeline_config:
      type: mapping
      label: 'TimelineJS presentation options'
      mapping:
        width:
          type: string
          label: 'Timeline width'
        height:
          type: string
          label: 'Timeline height'
        hash_bookmark:
          type: boolean
          label: 'Add bookmarkable slide URLs'
        start_at_end:
          type: boolean
          label: 'Initialize the timeline on the last slide'
        scale_factor:
          type: float
          label: 'How many screen widths wide the timeline should be upon first presentation'
        language:
          type: string
          label: 'Timeline language'
    additional_config:
      type: mapping
      label: 'Additional presentation options'
      mapping:
        font:
          type: string
          label: 'Timeline font set'
        start_at_current:
          type: boolean
          label: 'Initialize the timeline on the slide closest to the current date'
    timeline_fields:
      type: mapping
      label: 'Field mappings'
      mapping:
        caption:
          type: string
          label: 'Caption field'
        credit:
          type: string
          label: 'Credit field'
        media:
          type: string
          label: 'Media field'
        group:
          type: string
          label: 'Group field'
        start_date:
          type: string
          label: 'Start date field'
        end_date:
          type: string
          label: 'End date field'
        display_date:
          type: string
          label: 'Display date field'
        text:
          type: string
          label: 'Text field'
        headline:
          type: string
          label: 'Headline field'
        background:
          type: string
          label: 'Background image field'
        type:
          type: string
          label: 'Timeline entity type field'
        unique_id:
          type: string
          label: 'Unique ID field'
